// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MvcExampleML.Model
{
    public class ModelInput
    {
        [ColumnName("Date"), LoadColumn(0)]
        public float Date { get; set; }


        [ColumnName("Production"), LoadColumn(1)]
        public float Production { get; set; }


    }
}
